clientes/urls.py
from django.urls import path
from . import views as v

app_name ='clientes'

urlpatterns = [

    path('', v.clientes_List, name='clientes_list'),
    path('cadastrar/', v.ClienteCreate.as_view(), name='cliente_cadastrar'),
    path('deletar/<int:pk>', v.ClienteDelete.as_view(), name='cliente_deletar'),
    path('editar/<int:pk>', v.ClienteUpdate.as_view(), name='cliente_editar'),



]

pycrud/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls')),

]

clientes/models.py
from django.db import models
from django.urls import reverse_lazy


class Cliente(models.Model):
    objetcs = None
    nome = models.CharField(max_length=100)
    endereco = models.TextField()
    fone = models.CharField(max_length=10)
    email = models.CharField(max_length=20)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse_lazy('clientes:clientes_list')

clientes/forms.py
from django.forms import ModelForm
from .models import Cliente


class ClienteForm(ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'endereco', 'fone', 'email']

clientes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView

from .forms import ClienteForm
from .models import Cliente


def index(request):
    return HttpResponse("TESTE")


def clientes_List(request):
    template_name = 'clientes_list.html'
    objects = Cliente.objects.all()
    context = {'object_list': objects}

    return render(request, template_name, context)


def cliente_cadastrar(request):
    form = ClienteForm()
    template_name = 'cliente_form.html'

    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('cliente_list.html'))
    context = {'form': form}
    return render(request, template_name, context)


class ClienteCreate(CreateView):
    model = Cliente
    template_name = 'cliente_form.html'
    form_class = ClienteForm


class ClienteDelete(DeleteView):
    template_name = 'cliente_confirm_delete.html'
    model = Cliente
    success_url = reverse_lazy('clientes:clientes_list')


class ClienteUpdate(UpdateView):
    model = Cliente
    template_name = 'cliente_form.html'
    form_class = ClienteForm

clientes/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <h1>Hello, world!</h1>
    {% block content %}
    {% endblock content %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

clientes/templates/cliente_confirm_delete.html
<form method="POST" action="{% url 'clientes:cliente_deletar' cliente.id %}">
   {% csrf_token %}<input type="submit" value="DELETE">
</form>

clientes/templates/cliente_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Cadastre o cliente</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="cadastrar">
        </form>
    </div>
{% endblock %}

clientes/templates/clientes_list.html
{% extends 'base.html' %}

{% block content %}
 <table class="table table-dark">

  <div class="container">
      <a href="{% url 'clientes:cliente_cadastrar' %}">
        <button type="button" class="btn btn-success">Cadastrar</button>
      </a>
  </div>
  <thead>
    <tr>
        <th>Nome</th>
        <th>Endereço</th>
        <th>fone</th>
        <th>Email</th>
    </tr>
  </thead>

  <tbody>
    {% for cliente in object_list %}
    <tr>
     <td>{{ cliente.nome}} </td>
     <td>{{ cliente.endereco}} </td>
     <td>{{ cliente.fone}} </td>
     <td>{{ cliente.email}} </td>
     <td><a href="{% url 'clientes:cliente_editar' cliente.id %}">
         <button type="button" class="btn btn-primary">Editar</button>
     </a></td>
     <td><a href="{% url 'clientes:cliente_deletar' cliente.id %}">
         <button type="button" class="btn btn-danger">Deletar</button>
     </a>
     </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

clientes/templates/teste.html
<h1>TESTE</h1>